# Generated by Django 5.0 on 2023-12-13 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fatherName', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('motherName', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phone', models.IntegerField()),
                ('in_class', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=350)),
            ],
        ),
    ]
