# Generated by Django 5.0 on 2023-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_student_grade_student_chemisrty_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fatherName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='motherName',
            field=models.CharField(max_length=150),
        ),
    ]
