# Generated by Django 5.0 on 2023-12-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_fathername_alter_student_mothername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemistry',
            name='grade',
        ),
    ]
